{"name": "Создание заказа авторизованным пользователем", "status": "failed", "statusDetails": {"message": "AssertionError: assert (400 == 500)\n +  where 400 = <Response [400]>.status_code", "trace": "self = <tests.test_create_order.TestCreateOrder object at 0x107340050>\ncreate_and_delete_user = (['pittsdaniel144793r@example.net', '$(6Lzw0c', 'Zachary Vincent450710l'], {'accessToken': 'Bearer eyJhbGciOiJIUzI1NiI...de5fb35a931a', 'success': True, 'user': {'email': 'pittsdaniel144793r@example.net', 'name': 'Zachary Vincent450710l'}})\n\n    @allure.title(\"Создание заказа авторизованным пользователем\")\n    @allure.description(\"Передаются ингредиенты с неверным хешем\")\n    def test_create_order_auth_user_with_wrong_hash(self, create_and_delete_user):\n        auth_token = create_and_delete_user[1][\"accessToken\"]\n        headers = {\"Authorization\": f\"{auth_token}\"}\n        payload = {\n            \"ingredients\": [\"61c0c5a71d1f82001bdaaa00\"],  # <-- вынести в `data.py`\n        }\n        response = requests.post(\n            f\"{Urls.BASE}{Urls.CREATE_ORDER}\",\n            data=payload,\n            headers=headers,\n        )\n    \n        # В документации ожидается код ответа 500 почему-то, а в реальности сервер возвращет 400.\n        # Я проконсультровалась с наставником и он сказал проверять на код ответа как он описан в\n        # документации (даже если он очень странный - 500 - это ошибка сервера, а не запроса).\n        # Поэтому:\n        # (a) этот тест фейлится\n        # (b) проверяется на 500\n>       assert response.status_code == 500 and response.json() == DataMessage.MES_ONE_OR_MORE_IDS_PROVIDED_INCORRECT\nE       assert (400 == 500)\nE        +  where 400 = <Response [400]>.status_code\n\ntests/test_create_order.py:103: AssertionError"}, "description": "Передаются ингредиенты с неверным хешем", "start": 1740233985815, "stop": 1740233985981, "uuid": "e8d079f8-f8ef-41b1-b772-65bd201e1e29", "historyId": "d9c7dbf03e54aea67bee400c82396155", "testCaseId": "d9c7dbf03e54aea67bee400c82396155", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_auth_user_with_wrong_hash", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "Macbook-Pro-Denis"}, {"name": "thread", "value": "57256-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}